# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]




jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - run: cd api/
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: setup mysql database
      uses: mirromutth/mysql-action@v1.1
      with:
        # MYSQL_ROOT_PASSWORD - root superuser password
        mysql root password:  project_a
        # MYSQL_DATABASE - name for the default database that is created
        mysql database: project_a # optional, default is 
        # MYSQL_USER - create the specified user with superuser power for created database
        mysql user: project_a # optional, default is 
        # MYSQL_PASSWORD - specified superuser password which user is power for created database
        mysql password: project_a # optional, default is
    - run: npm test
